# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: approval.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'approval.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61pproval.proto\x12\x04\x61ria\"Y\n\x0f\x41pprovalRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x10\n\x08\x61pproved\x18\x02 \x01(\x08\x12\x13\n\x0breviewed_by\x18\x03 \x01(\t\x12\r\n\x05notes\x18\x04 \x01(\t\"B\n\rApprovalReply\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\"]\n\x0bPendingItem\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x13\n\x0buser_intent\x18\x02 \x01(\t\x12\x12\n\nrisk_score\x18\x03 \x01(\x05\x12\x13\n\x0b\x65xplanation\x18\x04 \x01(\t\"/\n\x0bPendingList\x12 \n\x05items\x18\x01 \x03(\x0b\x32\x11.aria.PendingItem2\x86\x01\n\x0f\x41pprovalService\x12<\n\x0eSubmitApproval\x12\x15.aria.ApprovalRequest\x1a\x13.aria.ApprovalReply\x12\x35\n\x13GetPendingApprovals\x12\x0b.aria.Empty\x1a\x11.aria.PendingListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'approval_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPROVALREQUEST']._serialized_start=24
  _globals['_APPROVALREQUEST']._serialized_end=113
  _globals['_APPROVALREPLY']._serialized_start=115
  _globals['_APPROVALREPLY']._serialized_end=181
  _globals['_EMPTY']._serialized_start=183
  _globals['_EMPTY']._serialized_end=190
  _globals['_PENDINGITEM']._serialized_start=192
  _globals['_PENDINGITEM']._serialized_end=285
  _globals['_PENDINGLIST']._serialized_start=287
  _globals['_PENDINGLIST']._serialized_end=334
  _globals['_APPROVALSERVICE']._serialized_start=337
  _globals['_APPROVALSERVICE']._serialized_end=471
# @@protoc_insertion_point(module_scope)
